### ISSUE TITLE
Youtube Module Bug

### ISSUE THREAD

**Issue by bymayfe** [Fabricio-191/youtube#1]
Hi,
I found a bug in the module. It has problems when it cannot attract the likes and dislikes.
I fix this bug and I want to deliver it to you. I will be glad if you contact me. Have a nice day.

Solved Codes

Lines 26/27

	const [likes, dislikes] = videoPrimaryInfoRenderer.sentimentBar
	? videoPrimaryInfoRenderer.sentimentBar.sentimentBarRenderer.tooltip.split(' / ').map(Utils.extractInt)
	: ["0","0"]

**Comment by Fabricio-191** [comment]
Can you tell me how to re-create this error ? so i can see it better

**Comment by Fabricio-191** [comment]
Can you tell me how to re-create this error ? (probably the video URL will be enough) so i can see it better, because if that's missing, there can be other things missing

**Comment by bymayfe** [comment]
### I apologize my computer has malfunctioned.

When the number of likes in the video was kept secret, it was giving an error because it could not pull the data.
Right now I have Flattened and reported it to you on my own computer. I recommend you to try a private video with the getVideo () function. Sample video: https://www.youtube.com/watch?v=Yoj-VLuCZvA
