### ISSUE TITLE
search bug

### ISSUE THREAD

**Issue by bymayfe** [Fabricio-191/youtube#3]
search playlist thumbnail 
![resim_2021-05-03_190106](https://user-images.githubusercontent.com/52834828/116900859-e92fae80-ac41-11eb-9087-0b101b40d985.png)

**Comment by bymayfe** [comment]
fixed code =>  

	thumbnails: new Utils.Thumbnails(
			playlistRenderer.thumbnailRenderer.playlistCustomThumbnailRenderer.thumbnail
		),

**Comment by bymayfe** [comment]
solved code => 

function playlistRenderer({ playlistRenderer }){
	var Thumbnailcik = playlistRenderer.thumbnailRenderer.playlistVideoThumbnailRenderer ? playlistRenderer.thumbnailRenderer.playlistVideoThumbnailRenderer.thumbnail : playlistRenderer.thumbnailRenderer.playlistCustomThumbnailRenderer.thumbnail

	return {
		ID: playlistRenderer.playlistId,
		URL: `https://www.youtube.com/playlist?list=${playlistRenderer.playlistId}`,
		title: Utils.parseText(playlistRenderer.title).toString(),

		type: 'playlist',
		videoCount: Number(playlistRenderer.videoCount),

		showedVideos: playlistRenderer.videos.map(childVideoRenderer),

		owner: bylineText(playlistRenderer),

		thumbnails: new Utils.Thumbnails(
			Thumbnailcik
		),
	};
}

**Comment by Fabricio-191** [comment]
You should send me the playlist url

**Comment by bymayfe** [comment]
bir damla umut

**Comment by Fabricio-191** [comment]
solved, but now i have finded the playlist and there is info missing when using the `getPlaylist`, i will fix it an then update

**Comment by Fabricio-191** [comment]
Done 👌
